In [1]:
import pycaret
import pandas
from pycaret.classification import *

In [2]:
df = pd.read_csv('reussite_classi.csv')
df = df.drop(['Unnamed: 0'], axis=1)
df

,body,polarity,subjectivity,grade,eligibility
0,"Bonjour,\nJe suis sur mac OSx 10,12 Sierra et ...",-1.000000,0.350000,0.45,0
1,Je viens de lancer un S.O.S et j'ai omis de me...,1.000000,0.100000,0.45,0
2,"Merci Michaël, cela à fonctionné; ""y'a plus k""...",1.000000,0.150000,0.45,0
3,"Bonjour,\nJe suis sur mac OSx 10,12 Sierra et ...",-1.000000,0.350000,0.13,0
4,Je viens de lancer un S.O.S et j'ai omis de me...,1.000000,0.100000,0.13,0
...,...,...,...,...,...
24860,Merci pour ce lien de l'intervention K. Robins...,0.000000,0.600000,0.73,1
24861,Merci pour ce lien de l'intervention K. Robins...,0.000000,0.600000,0.00,0
24862,Pas tout à fait d'accord sur l'évaluation de l...,-0.157895,0.186429,0.90,1
24863,Pas tout à fait d'accord sur l'évaluation de l...,-0.157895,0.186429,0.93,1
24864,Pas tout à fait d'accord sur l'évaluation de l...,-0.157895,0.186429,0.97,1

In [3]:
report = setup(data=df, target="eligibility")

In [4]:
compare_models()

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=8270, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)